apiVersion: v1
kind: Service
metadata:
  name: tcp-pool-proxy
spec:
  ports:
  - port: 8443
    targetPort: 8443
    nodePort: 30104
    protocol: TCP
  selector:
    app: tcp-pool-proxy
  type: NodePort