apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: aws-container-factory
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:latest
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379