apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: aws-container-factory
spec:
  ports:
  - port: 3000
    name: grafana
    targetPort: 3000
    protocol: TCP
    nodePort: 30103
  selector:
    app: grafana
  type: NodePort