apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: aws-container-factory
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana:latest
        imagePullPolicy: Always
        name: grafana
        ports:
        - containerPort: 3000
        env:
        - name: INFLUXDB_HOST
          value: influxdb