apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  ports:
  - port: 8089
    name: non-admin-udp-port
    targetPort: 8089
    nodePort: 30102
    protocol: UDP
  - port: 8086
    name: non-admin-http-port
    targetPort: 8086
    nodePort: 30100
    protocol: TCP
  - port: 8083
    name: admin-port
    targetPort: 8083
    nodePort: 30101
    protocol: TCP
  - port: 2003
    name: graphite-port
    targetPort: 2003
    protocol: TCP
  selector:
    app: influxdb
  type: NodePort