apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-api
  namespace: aws-container-factory
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
      - image: nextmetaphor/simple-golang-api:latest
        imagePullPolicy: Always
        name: sample-api
        ports:
        - containerPort: 8080